### ISSUE TITLE
Question about paper-SMO&MA for IR modality in Table V

### ISSUE THREAD

**Issue by zjh21** [VisDrone/DroneVehicle#38]
Thank you very much for your great work.
I am wondering why SMO and MA can be applied to the IR modality in Table V, since Winf = 1 and there is no misalignment weight for the IR modality. 
Besides, it would be very much appreciated if you can tell me what instances are used for calculating mAP? Is it all instances from RGB and IR annotations, filtered with NMS?

感谢您的精彩工作。
我很好奇论文中表V里，为什么SMO和MA可以用在IR波段上，因为Winf是1，也就是SMO不对IR中没有标注的目标加上权重，而且IR波段好像也没有不配准的权重。
另外，能否告知哪些目标用于计算mAP？是RGB和IR标注中所有的目标整合在一起，用NMS过滤一下吗？非常感谢！

**Comment by SunYM2020** [comment]
Thank you for your attention to our work.
1. Please refer to the official version of our paper at https://ieeexplore.ieee.org/abstract/document/9759286.
2. We use GroundTruth of infrared modality to evaluate model performance.

**Comment by zjh21** [comment]
> Thank you for your attention to our work.
> 
>     1. Please refer to the official version of our paper at https://ieeexplore.ieee.org/abstract/document/9759286.
> 
>     2. We use GroundTruth of infrared modality to evaluate model performance.

Thank you for answering the question. I understand your work better now.
