### ISSUE TITLE
When can I download the dataset?

### ISSUE THREAD

**Issue by Pluto1314** [VisDrone/DroneVehicle#4]
Hello, I think this is a good work!
It is May now. When can I download it?

**Comment by qgh1223** [comment]
I'm also interested in your dataset

**Comment by 121786404** [comment]
20200704

**Comment by zhongwenkun886** [comment]
Looking forward to it too!

**Comment by zyx1996** [comment]
20200901

**Comment by shaojiestar** [comment]
20201030
